spring.application.name=tickeria-backend

# Conectarse al MySQL de Docker usando el puerto alternativo 3307
spring.datasource.url=jdbc:mysql://localhost:3307/tickeria_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=tickeria_user
spring.datasource.password=tickeria_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate creará las tablas automáticamente en tu base de datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect