# TECNOLOGÍA: Spring Boot Configuration / JDBC / Hibernate
# PROPÓSITO: Configurar las credenciales de conexión segura a la base de datos de Docker.
# Define la estrategia 'update' de Hibernate para crear/modificar tablas SQL automáticamente en base a las entidades Java.

spring.application.name=tickeria-backend

# Conectarse al MySQL de Docker usando el puerto alternativo 3307
#spring.datasource.url=jdbc:mysql://localhost:3307/tickeria_db?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=tickeria_user
#spring.datasource.password=tickeria_password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://database:3306/tickeria_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=tickeria_user
spring.datasource.password=tickeria_password

# Hibernate creará las tablas automáticamente en tu base de datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

